
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Package
 * 
 */
export type Package = Prisma.PackageModel
/**
 * Model Bookings
 * 
 */
export type Bookings = Prisma.BookingsModel
/**
 * Model Payment
 * 
 */
export type Payment = Prisma.PaymentModel
/**
 * Model DayItinerary
 * 
 */
export type DayItinerary = Prisma.DayItineraryModel
/**
 * Model FeaturedItems
 * 
 */
export type FeaturedItems = Prisma.FeaturedItemsModel
/**
 * Model IncludedItems
 * 
 */
export type IncludedItems = Prisma.IncludedItemsModel
/**
 * Model ExcludedItems
 * 
 */
export type ExcludedItems = Prisma.ExcludedItemsModel
/**
 * Model Blogs
 * 
 */
export type Blogs = Prisma.BlogsModel
/**
 * Model BlogImages
 * 
 */
export type BlogImages = Prisma.BlogImagesModel
/**
 * Model BlogCategory
 * 
 */
export type BlogCategory = Prisma.BlogCategoryModel
/**
 * Model Destinations
 * 
 */
export type Destinations = Prisma.DestinationsModel
/**
 * Model DestinationFAQ
 * 
 */
export type DestinationFAQ = Prisma.DestinationFAQModel
/**
 * Model Testimonials
 * 
 */
export type Testimonials = Prisma.TestimonialsModel
