
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Package'
export type * from './models/Bookings'
export type * from './models/Payment'
export type * from './models/DayItinerary'
export type * from './models/FeaturedItems'
export type * from './models/IncludedItems'
export type * from './models/ExcludedItems'
export type * from './models/Blogs'
export type * from './models/BlogImages'
export type * from './models/BlogCategory'
export type * from './models/Destinations'
export type * from './models/DestinationFAQ'
export type * from './models/Testimonials'
export type * from './commonInputTypes'