
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  Package: 'Package',
  Bookings: 'Bookings',
  Payment: 'Payment',
  DayItinerary: 'DayItinerary',
  FeaturedItems: 'FeaturedItems',
  IncludedItems: 'IncludedItems',
  ExcludedItems: 'ExcludedItems',
  Blogs: 'Blogs',
  BlogImages: 'BlogImages',
  BlogCategory: 'BlogCategory',
  Destinations: 'Destinations',
  DestinationFAQ: 'DestinationFAQ',
  Testimonials: 'Testimonials'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const PackageScalarFieldEnum = {
  id: 'id',
  name: 'name',
  days: 'days',
  nights: 'nights',
  image: 'image',
  price: 'price',
  type: 'type',
  location: 'location',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PackageScalarFieldEnum = (typeof PackageScalarFieldEnum)[keyof typeof PackageScalarFieldEnum]


export const BookingsScalarFieldEnum = {
  id: 'id',
  customerName: 'customerName',
  customerEmail: 'customerEmail',
  customerPhone: 'customerPhone',
  numberOfPeople: 'numberOfPeople',
  paid: 'paid',
  packageId: 'packageId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BookingsScalarFieldEnum = (typeof BookingsScalarFieldEnum)[keyof typeof BookingsScalarFieldEnum]


export const PaymentScalarFieldEnum = {
  id: 'id',
  amount: 'amount',
  paid: 'paid',
  paymentMethod: 'paymentMethod',
  razorpayPaymentId: 'razorpayPaymentId',
  paymentDate: 'paymentDate',
  bookingId: 'bookingId',
  createdAt: 'createdAt'
} as const

export type PaymentScalarFieldEnum = (typeof PaymentScalarFieldEnum)[keyof typeof PaymentScalarFieldEnum]


export const DayItineraryScalarFieldEnum = {
  id: 'id',
  dayNumber: 'dayNumber',
  description: 'description',
  packageId: 'packageId'
} as const

export type DayItineraryScalarFieldEnum = (typeof DayItineraryScalarFieldEnum)[keyof typeof DayItineraryScalarFieldEnum]


export const FeaturedItemsScalarFieldEnum = {
  id: 'id',
  item: 'item',
  dayItineraryId: 'dayItineraryId'
} as const

export type FeaturedItemsScalarFieldEnum = (typeof FeaturedItemsScalarFieldEnum)[keyof typeof FeaturedItemsScalarFieldEnum]


export const IncludedItemsScalarFieldEnum = {
  id: 'id',
  item: 'item',
  packageId: 'packageId'
} as const

export type IncludedItemsScalarFieldEnum = (typeof IncludedItemsScalarFieldEnum)[keyof typeof IncludedItemsScalarFieldEnum]


export const ExcludedItemsScalarFieldEnum = {
  id: 'id',
  item: 'item',
  packageId: 'packageId'
} as const

export type ExcludedItemsScalarFieldEnum = (typeof ExcludedItemsScalarFieldEnum)[keyof typeof ExcludedItemsScalarFieldEnum]


export const BlogsScalarFieldEnum = {
  id: 'id',
  title: 'title',
  html: 'html',
  thumbnail: 'thumbnail',
  customerName: 'customerName',
  feedback: 'feedback',
  author: 'author',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BlogsScalarFieldEnum = (typeof BlogsScalarFieldEnum)[keyof typeof BlogsScalarFieldEnum]


export const BlogImagesScalarFieldEnum = {
  id: 'id',
  url: 'url',
  blogId: 'blogId'
} as const

export type BlogImagesScalarFieldEnum = (typeof BlogImagesScalarFieldEnum)[keyof typeof BlogImagesScalarFieldEnum]


export const BlogCategoryScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type BlogCategoryScalarFieldEnum = (typeof BlogCategoryScalarFieldEnum)[keyof typeof BlogCategoryScalarFieldEnum]


export const DestinationsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  tag: 'tag',
  title: 'title',
  description: 'description',
  image: 'image',
  country: 'country',
  visa: 'visa',
  languagesSpoken: 'languagesSpoken',
  currency: 'currency',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DestinationsScalarFieldEnum = (typeof DestinationsScalarFieldEnum)[keyof typeof DestinationsScalarFieldEnum]


export const DestinationFAQScalarFieldEnum = {
  id: 'id',
  question: 'question',
  answer: 'answer',
  destinationId: 'destinationId'
} as const

export type DestinationFAQScalarFieldEnum = (typeof DestinationFAQScalarFieldEnum)[keyof typeof DestinationFAQScalarFieldEnum]


export const TestimonialsScalarFieldEnum = {
  id: 'id',
  customerName: 'customerName',
  feedback: 'feedback',
  rating: 'rating',
  image: 'image',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TestimonialsScalarFieldEnum = (typeof TestimonialsScalarFieldEnum)[keyof typeof TestimonialsScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

